### ISSUE TITLE
3.0.10歌词不显示

### ISSUE THREAD

**Issue by Dusttear** [Xposed-Modules-Repo/cn.aodlyric.xiaowine#3]
重启万象息屏，sysui都不行，息屏不显示歌词，状态栏歌词正常，上个版本还能正常显示

**Comment by Dusttear** [comment]
> 重启万象息屏，sysui都不行，息屏不显示歌词，状态栏歌词正常，上个版本还能正常显示

作者大大，能解决一下吗？（是只有我才遇到这个问题吗？）

**Comment by TanZhiwen2001** [comment]
> > 重启万象息屏，sysui都不行，息屏不显示歌词，状态栏歌词正常，上个版本还能正常显示
> 
> 作者大大，能解决一下吗？（是只有我才遇到这个问题吗？）

我的也不显示

**Comment by cmmdwl** [comment]
不显示+1 同样问题，电池信息和一言正常显示，可排除没有hook上aod，怀疑每收到歌词的hook有问题，但状态栏歌词工作正常，墨息软件内没法点击Lyrics Getter 怀疑跳转没做好？

**Comment by Dusttear** [comment]
用了几天下来，状态栏歌词也时常不显示，重启sysui后正常
